### ISSUE TITLE
Fail download

### ISSUE THREAD

**Issue by turpez** [borderline232/fetscraper#2]
<Response [403]>
Traceback (most recent call last):
  File "C:\Users\utilisateur\Documents\Python test\fetscraper\fetscrape-image-profile.py", line 153, in <module>
    main(username, password, url, directory)
  File "C:\Users\utilisateur\Documents\Python test\fetscraper\fetscrape-image-profile.py", line 60, in main
    login_data['authenticity_token'] = soup.find('input', attrs={'name': 'authenticity_token'})['value']
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by Jamarzz** [comment]
I'm also experiencing this issue.
